### ISSUE TITLE
Plugin doesn't delete old backups

### ISSUE THREAD

**Issue by Generator** [jnko/SimpleDatabaseBackup#4]
I'm on Archlinux and SimpleDatabaseBackup isn't removing the old backups, only creates new ones.  
The logfile only shows the last six!  

**Directory files:**

    kpdb_13-Janeiro-2017-07-07-36.kdbx
    kpdb_13-Janeiro-2017-07-16-56.kdbx
    kpdb_13-Janeiro-2017-07-18-23.kdbx
    kpdb_13-Janeiro-2017-07-28-58.kdbx
    kpdb_13-Janeiro-2017-07-29-42.kdbx
    kpdb_13-Janeiro-2017-07-44-42.kdbx
    kpdb_14-Janeiro-2017-06-10-34.kdbx
    kpdb_14-Janeiro-2017-10-40-24.kdbx
    kpdb_22-Janeiro-2017-07-45-16.kdbx
    kpdb_22-Janeiro-2017-08-06-25.kdbx
    kpdb_22-Janeiro-2017-09-50-25.kdbx
    kpdb_23-Janeiro-2017-01-50-41.kdbx
    kpdb_23-Janeiro-2017-07-22-46.kdbx
    kpdb_25-Janeiro-2017-07-18-40.kdbx
    kpdb_26-Janeiro-2017-01-30-58.kdbx
    kpdb_27-Janeiro-2017-01-45-45.kdbx
    kpdb.kdbx
    kpdb.kdbx_log
    kpdb_13-Janeiro-2017-05-45-07.kdbx 

**logfile:**

    kpdb_27-Janeiro-2017-01-45-45.kdbx
    kpdb_26-Janeiro-2017-01-30-58.kdbx
    kpdb_25-Janeiro-2017-07-18-40.kdbx
    kpdb_23-Janeiro-2017-07-22-46.kdbx
    kpdb_23-Janeiro-2017-01-50-41.kdbx
    kpdb_22-Janeiro-2017-09-50-25.kdbx

**Envoriment:**
Archlinux
mono 4.6.1.3
KeePass 2.35

**Comment by jnko** [comment]
Is there any synchronization tool running ? (OwnCloud/NextCloud ect.)
I cannot reproduce the problem right now, perhaps you can provide some more information on how to reproduce these behavior please?

We`re running this plugin in a group of three people, with both a personal and a shared kdbx database synced over webdav and nextcloud client and never had a similar issue.

**Comment by greatvc** [comment]
Yes i have the same issue. I have 6 backups now on my folder. The database file is on a google drive so sync is there if that is an issue

**Comment by jnko** [comment]
This is by design when the KPDatabase is located in a synchronized foleder (ownCloud/Nextcloud/Dropbox/...).
The logfile is being overwritten (synced) with backup-information from another client.
The solution would be to save the logfile in a systems temp folder instead into the synced folder.
This way there are max. 5 backups _per client_ in the synced folder, but this seems to be the only way to ensure that every saving is being backed up. Perhaps with the clients hostname mentioned in the filename.

Anyway I will fix this soon. Please stay tuned...

**Comment by greatvc** [comment]
hi jnko, any news on this? I just tested it on my second keepass database and no old backups are deleted.
thanks.

**Comment by jnko** [comment]
Well, yes ;-) Currently I've not very much time but this morning I spent 1/2 hour.

I've completely rewritten the logic.
From now whenever you save a file SDB will list all backup files and deletes every old dbbackup > maxbackups.

 It works for me here but I need some "beta testers".

1. Manually delete all database backup files.
2. Delete the logfile. It isn't needed anymore
3. Copy your real KeePass databases to a safe place! It's for your insurance!
4. Replace the SimpleDatabaseBackup.plgx with the one included in the .zip file
[SimpleDatabaseBackup.zip](https://github.com/jnko/SimpleDatabaseBackup/files/816114/SimpleDatabaseBackup.zip)
5. Report back please

**Comment by greatvc** [comment]
I tried with a test database on google drive. At first save i get this error attach.
Then for a few saves later i get no error, and then the same error again.
It still doesn't delete old databases i have a folder with 7 database file

![image](https://cloud.githubusercontent.com/assets/13116317/23543064/141f9d3e-fff9-11e6-8437-0eb62161a07e.png)

![image](https://cloud.githubusercontent.com/assets/13116317/23543073/1b19fe36-fff9-11e6-87b4-811645e2cda6.png)

**Comment by jnko** [comment]
...Seems I need to use GoogleDrive for testing...
Cloud you please describe your setup?
One or more clients ?
KeePass.exe and it's database(s) in GoogleDrive folder?
anything more I need to know?

Thanks for testing!

**Comment by greatvc** [comment]
so i have the keepass installed on c:\program files as normal. The database is saved on the google drive folder which is a local path c:\users\usename\google drive\keepass database. then the google drive app syncs the file stored in that folder to the cloud.
That is my personal database, and i have another instance of keepass with a database stored on onedrive which follows the same principal as google drive.

That is on my work laptop, i follow the same principal on my home desktop thats why i have the databases on cloud in order to be in sync with both windows 10, 32bit 64bit fully updated with latest version of keepass application.

**Comment by jnko** [comment]
Hmmm... I'm a little bit confused about that "Failed to save the current database" message. It's not from me but probably from KeePass.

Anyway here's another shot. Don' worry about that many dialog boxes - they are for debugging only.

[SimpleDatabaseBackupBetaDebug.zip](https://github.com/jnko/SimpleDatabaseBackup/files/816272/SimpleDatabaseBackupBetaDebug.zip)

**Comment by greatvc** [comment]
no error this time, i do not know what was that maybe it is a bug of keepass.
Older databases were deleted now with no issue. tried on my google drive folder, i suppose the same will apply on the onedrive as well.

![image](https://cloud.githubusercontent.com/assets/13116317/23545075/785804b8-0002-11e7-82d1-ede1eb8c2853.png)

Should i keep the zip or you will push a new version that i will be notified ?

**Comment by jnko** [comment]
Well the deleting thing was my fault.
I'm preparing the new release 1.0.7 now which should become available within in the next hour.

Thanks for testing and enjoy using!
